Add joining to team
TheBestTvarynka/eshka pull request #24
Opened 2020-11-09 20:22 UTC by Makse3351

2020-11-09 20:24 UTC, IvanLuchkin approved these changes, later dismissed

2020-11-09 20:28 UTC, TheBestTvarynka requested changes
:writing_hand:

2020-11-09 20:28 UTC, TheBestTvarynka commented on backend/src/main/java/com/eshka/entity/User.java
> +    private Long teamId;
Here should be `Team team` instead of `Long teamId`.
Also, don't forget to specify relationship type.

2020-11-09 20:28 UTC, TheBestTvarynka commented on backend/src/main/java/com/eshka/service/TeamService.java
> +    void joinToTeam(User user,String link);
`User user,String link` -> `User user, String link`

2020-11-09 20:28 UTC, TheBestTvarynka commented on backend/src/main/resources/application.properties
> +server.port=8080
You should never commit changes in `application.properties` file!

2020-11-09 20:31 UTC, TheBestTvarynka commented on backend/src/main/java/com/eshka/entity/User.java
> +    private Long teamId;
```java
@ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.MERGE, CascadeType.PERSIST})
@JoinColumn(name = "team_id")
private Team team;
```

2020-11-11 09:21 UTC, TheBestTvarynka commented on backend/src/main/java/com/eshka/entity/User.java
> +            name = "TeamToUser",
Table name should start from the lower case letter.

2020-11-11 09:21 UTC, TheBestTvarynka commented on backend/src/main/java/com/eshka/service/TeamService.java
> +    void joinToTeam(User user,String link);
Add space, please)

2020-11-11 09:36 UTC, TheBestTvarynka commented
:-1:

2020-11-13 20:10 UTC, TheBestTvarynka reviewed
:raccoon:

2020-11-13 20:10 UTC, TheBestTvarynka approved these changes
:raccoon:

2020-11-13 20:10 UTC, merged