Finalize teams & subjects frontend
TheBestTvarynka/eshka pull request #32
Opened 2020-11-20 22:46 UTC by TheBestTvarynka

2020-11-21 21:15 UTC, KySo4oK requested changes
What is happening when front-ender trying to wrote smt in back-end

2020-11-21 21:15 UTC, KySo4oK commented on backend/src/main/java/com/eshka/controller/AuthController.java
> +        System.out.println("Log Out");
unacceptable

2020-11-21 21:15 UTC, KySo4oK commented on backend/src/main/java/com/eshka/controller/TeamController.java
> +    public ResponseEntity<TeamFullResponse> getFullInfo(@PathVariable(name = "id") String id) {
teamId is better name

2020-11-21 21:15 UTC, KySo4oK commented on backend/src/main/java/com/eshka/dto/response/TeamFullResponse.java
> +                team.getSubjects().stream()
unacceptable for entity class. This Business Logic must be in Services or mapper

2020-11-21 21:15 UTC, KySo4oK commented on backend/src/main/java/com/eshka/mapper/TeamMapper.java
> +}
what was changed?)

2020-11-21 21:15 UTC, KySo4oK commented on backend/src/main/java/com/eshka/service/impl/TeamServiceImpl.java
> +    // @Value("${HOST}")
why u comment it?

2020-11-27 13:31 UTC, TheBestTvarynka commented on backend/src/main/java/com/eshka/controller/TeamController.java
> +    public ResponseEntity<TeamFullResponse> getFullInfo(@PathVariable(name = "id") String id) {
Okay, I'll fix it.

2020-11-27 13:31 UTC, TheBestTvarynka commented on backend/src/main/java/com/eshka/controller/AuthController.java
> +        System.out.println("Log Out");
uups

2020-11-27 13:32 UTC, TheBestTvarynka commented on backend/src/main/java/com/eshka/mapper/TeamMapper.java
> +}
I don't know(

2020-11-27 16:55 UTC, KySo4oK commented on backend/src/main/java/com/eshka/controller/AuthController.java
> +    public void logout() {
empty method?)

2020-11-27 16:58 UTC, KySo4oK approved these changes

2020-11-27 20:31 UTC, merged